---

- name: Put in place certbot renewal cron job script
  template:
    src: "certbot_renew.j2"
    dest: "/usr/local/bin/certbot_renew"
    owner: "root"
    group: "root"
    mode: "0750"

- name: Create cron job for certificate renewal
  cron:
    name: "Certbot certificate renewal"
    job: "{{ certbot_cron_renew_command }}"
    minute: "{{ certbot_cron_renew_minute }}"
    hour: "{{ certbot_cron_renew_hour }}"
    user: "{{ certbot_cron_renew_user }}"
