---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint -c ./molecule/default/yaml-lint.yml .
  ansible-lint
platforms:
  - name: instance
    image: docker.io/pycontribs/centos:7
    privileged: true
    pre_build_image: true
    volume:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
