---
name: CI
'on':
  pull_request:
  push:
    branches:
      - master

jobs:
  molecule_test:
    name: Molecule Ansible Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out the ansible role repo
        uses: actions/checkout@v2
      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install molecule test dependencies
        run: pip3 install molecule[docker] yamllint ansible-lint
      - name: Run molecule tests
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
